# Generated by Django 5.2.4 on 2025-07-28 07:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_categories', to='organisations.organisation')),
            ],
            options={
                'verbose_name_plural': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('subcategory_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategories', to='products.productcategory')),
                ('organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='organisations.organisation')),
            ],
            options={
                'verbose_name_plural': 'product_subcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('mfg', models.DateField(default=datetime.date.today)),
                ('product_life', models.PositiveIntegerField(default=1)),
                ('product_image1', models.TextField(blank=True, null=True)),
                ('product_image2', models.TextField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('organic', 'Organic'), ('non-organic', 'Non-Organic')], default='organic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.TextField(blank=True, null=True)),
                ('subcategory_name', models.TextField(blank=True, null=True)),
                ('organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='organisations.organisation')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productsubcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
